//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.BL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.BL.Properties.Resources.", typeof(Resources_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn maximaal 100 tekens toegestaan.
        /// </summary>
        public static string D_t_ErrorMessage {
            get {
                return ResourceManager.GetString("D_t_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string D_tr_DateString {
            get {
                return ResourceManager.GetString("D_tr_DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan niet voor de datum dat het ticket is gecreërd!.
        /// </summary>
        public static string D_tr_ValidationResult {
            get {
                return ResourceManager.GetString("D_tr_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik dit gebied om extra informatie te verschaffen..
        /// </summary>
        public static string MVC_h_AboutContent {
            get {
                return ResourceManager.GetString("MVC_h_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string MVC_h_AboutTitle {
            get {
                return ResourceManager.GetString("MVC_h_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle tickets.
        /// </summary>
        public static string MVC_h_ActionLinkAllTickets {
            get {
                return ResourceManager.GetString("MVC_h_ActionLinkAllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak aan.
        /// </summary>
        public static string MVC_h_ActionLinkCreate {
            get {
                return ResourceManager.GetString("MVC_h_ActionLinkCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle tickets.
        /// </summary>
        public static string MVC_h_AllTickets {
            get {
                return ResourceManager.GetString("MVC_h_AllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toont een lijst van alle bestaande tickets..
        /// </summary>
        public static string MVC_h_AllTicketsInfo {
            get {
                return ResourceManager.GetString("MVC_h_AllTicketsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:.
        /// </summary>
        public static string MVC_h_ContactPhoneContent {
            get {
                return ResourceManager.GetString("MVC_h_ContactPhoneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoon.
        /// </summary>
        public static string MVC_h_ContactPhoneTitle {
            get {
                return ResourceManager.GetString("MVC_h_ContactPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MVC_h_ContactTitle {
            get {
                return ResourceManager.GetString("MVC_h_ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon ticket.
        /// </summary>
        public static string MVC_h_FormBttnValue {
            get {
                return ResourceManager.GetString("MVC_h_FormBttnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketnummer.
        /// </summary>
        public static string MVC_h_FormIdLabel {
            get {
                return ResourceManager.GetString("MVC_h_FormIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string MVC_h_IndexTitle {
            get {
                return ResourceManager.GetString("MVC_h_IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkoop:.
        /// </summary>
        public static string MVC_h_Marketing {
            get {
                return ResourceManager.GetString("MVC_h_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw ticket.
        /// </summary>
        public static string MVC_h_NewTicket {
            get {
                return ResourceManager.GetString("MVC_h_NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw ticket aan in het systeem..
        /// </summary>
        public static string MVC_h_NewTicketInfo {
            get {
                return ResourceManager.GetString("MVC_h_NewTicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon ticket.
        /// </summary>
        public static string MVC_h_ShowTicket {
            get {
                return ResourceManager.GetString("MVC_h_ShowTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geeft de details van één ticket..
        /// </summary>
        public static string MVC_h_ShowTicketInfo {
            get {
                return ResourceManager.GetString("MVC_h_ShowTicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondersteuning:.
        /// </summary>
        public static string MVC_h_Support {
            get {
                return ResourceManager.GetString("MVC_h_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpcentrum.
        /// </summary>
        public static string MVC_h_SupportCenter {
            get {
                return ResourceManager.GetString("MVC_h_SupportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom op het online helpdesk systeem..
        /// </summary>
        public static string MVC_h_WelcomeMssgIndex {
            get {
                return ResourceManager.GetString("MVC_h_WelcomeMssgIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je applicatie descriptiepagina..
        /// </summary>
        public static string MVC_hc_AboutMessage {
            get {
                return ResourceManager.GetString("MVC_hc_AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je contactpagina..
        /// </summary>
        public static string MVC_hc_ContactMessage {
            get {
                return ResourceManager.GetString("MVC_hc_ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout..
        /// </summary>
        public static string MVC_s_ErrorH1 {
            get {
                return ResourceManager.GetString("MVC_s_ErrorH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden tijdens het verwerken van je aanvraag..
        /// </summary>
        public static string MVC_s_ErrorH2 {
            get {
                return ResourceManager.GetString("MVC_s_ErrorH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout.
        /// </summary>
        public static string MVC_s_ErrorTitle {
            get {
                return ResourceManager.GetString("MVC_s_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar de lijst.
        /// </summary>
        public static string MVC_t_ActionLickBack {
            get {
                return ResourceManager.GetString("MVC_t_ActionLickBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas aan.
        /// </summary>
        public static string MVC_t_ActionLinkEdit {
            get {
                return ResourceManager.GetString("MVC_t_ActionLinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps, er liep iets verkeerd!.
        /// </summary>
        public static string MVC_t_Alert {
            get {
                return ResourceManager.GetString("MVC_t_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmaken.
        /// </summary>
        public static string MVC_t_CreateNew {
            get {
                return ResourceManager.GetString("MVC_t_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder.
        /// </summary>
        public static string MVC_t_DeleteBttn {
            get {
                return ResourceManager.GetString("MVC_t_DeleteBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit wilt verwijderen?.
        /// </summary>
        public static string MVC_t_DeleteH2 {
            get {
                return ResourceManager.GetString("MVC_t_DeleteH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string MVC_t_DetailsTitle {
            get {
                return ResourceManager.GetString("MVC_t_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string MVC_t_IndexTitle {
            get {
                return ResourceManager.GetString("MVC_t_IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is door een klant beantwoord.
        /// </summary>
        public static string MVC_t_IsClientResponse {
            get {
                return ResourceManager.GetString("MVC_t_IsClientResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laad antwoorden.
        /// </summary>
        public static string MVC_t_LoadAnswerBttn {
            get {
                return ResourceManager.GetString("MVC_t_LoadAnswerBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sla op.
        /// </summary>
        public static string MVC_t_SaveBttn {
            get {
                return ResourceManager.GetString("MVC_t_SaveBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzenden.
        /// </summary>
        public static string MVC_t_Send {
            get {
                return ResourceManager.GetString("MVC_t_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string MVC_t_TicketH4 {
            get {
                return ResourceManager.GetString("MVC_t_TicketH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgelopen bij het registreren van het antwoord!.
        /// </summary>
        public static string MVC_trc_BadRequest {
            get {
                return ResourceManager.GetString("MVC_trc_BadRequest", resourceCulture);
            }
        }
    }
}
