//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.UI.CA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.UI.CA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keuze: .
        /// </summary>
        internal static string AskChoice {
            get {
                return ResourceManager.GetString("AskChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van het toestel: .
        /// </summary>
        internal static string AskDeviceName {
            get {
                return ResourceManager.GetString("AskDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is het een hardware probleem (j/n)? .
        /// </summary>
        internal static string AskIfHardwareIssue {
            get {
                return ResourceManager.GetString("AskIfHardwareIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probleem: .
        /// </summary>
        internal static string AskProblem {
            get {
                return ResourceManager.GetString("AskProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwoord: .
        /// </summary>
        internal static string AskResponse {
            get {
                return ResourceManager.GetString("AskResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketnummer: .
        /// </summary>
        internal static string AskTicketnumber {
            get {
                return ResourceManager.GetString("AskTicketnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnummer: .
        /// </summary>
        internal static string AskUsernumber {
            get {
                return ResourceManager.GetString("AskUsernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies uw taal.
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klant.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markeer ticket als &apos;Closed&apos;.
        /// </summary>
        internal static string CloseTicket {
            get {
                return ResourceManager.GetString("CloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toestel.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engels.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELPDESK - SUPPORT CENTER.
        /// </summary>
        internal static string Helpdesk {
            get {
                return ResourceManager.GetString("Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen geldige keuze!.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language is now set to English..
        /// </summary>
        internal static string LangChosen {
            get {
                return ResourceManager.GetString("LangChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talen: .
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef een antwoord op een ticket.
        /// </summary>
        internal static string MakeNewResponse {
            get {
                return ResourceManager.GetString("MakeNewResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw ticket.
        /// </summary>
        internal static string MakeNewTicket {
            get {
                return ResourceManager.GetString("MakeNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vraag/probleem.
        /// </summary>
        internal static string QuestionOrProblem {
            get {
                return ResourceManager.GetString("QuestionOrProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antwoorden.
        /// </summary>
        internal static string Responses {
            get {
                return ResourceManager.GetString("Responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon alle tickets.
        /// </summary>
        internal static string ShowAllTickets {
            get {
                return ResourceManager.GetString("ShowAllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon details van een ticket.
        /// </summary>
        internal static string ShowTicketDetails {
            get {
                return ResourceManager.GetString("ShowTicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon de antwoorden van een ticket.
        /// </summary>
        internal static string ShowTicketResponses {
            get {
                return ResourceManager.GetString("ShowTicketResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        internal static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er heeft zich een onverwachte fout voorgedaan!.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
